<a href="https://colab.research.google.com/github/Ssurf777/pytorch_tensorflow_MLP_compare/blob/main/Pytorch_tensor%E6%93%8D%E4%BD%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ライブラリのインポート

In [ ]:
import torch
import numpy as np

# ①定義

In [ ]:
npdata = np.array([[0,1,2],[3,4,5]])
tendata = torch.tensor([[0,1,2],[3,4,5]])

In [ ]:
npzero = np.zeros((2,3))
tenzero = torch.zeros((2,3))

In [ ]:
npran = np.random.rand(2,3)
tenran = torch.rand((2,3))

In [ ]:
npone = np.ones((2,3))
tenone = torch.ones((2,3))

In [ ]:
tenone

tensor([[1., 1., 1.],
        [1., 1., 1.]])

# ②tensorのサイズ，タイプ等の確認

In [ ]:
npdata.shape

(2, 3)

In [ ]:
tendata.shape

torch.Size([2, 3])

In [ ]:
npdata.dtype

dtype('int64')

In [ ]:
tendata.dtype

torch.int64

In [ ]:
type(npdata)

numpy.ndarray

In [ ]:
type(tendata)

torch.Tensor

# ③tensor　 ↔️　numpy.array 変換


In [ ]:
# tensorで宣言
before = torch.zeros(3)
before

tensor([0., 0., 0.])

In [ ]:
# tensorからnumpyに変換
after = before.numpy()
after

array([0., 0., 0.], dtype=float32)

In [ ]:
# NumpyからTensorに変換
change = torch.from_numpy(after)
change

tensor([0., 0., 0.])

In [ ]:
# pandas dataframe → numpy array
import pandas as pd
dict1 = {"a":[1,2,3],"b":[1,2,3],"c":[1,2,3]}
df = pd.DataFrame(dict1)
arr = df.to_numpy()
arrcha = torch.from_numpy(arr)

In [ ]:
df

a  b  c
0  1  1  1
1  2  2  2
2  3  3  3

In [ ]:
arr

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [ ]:
arrcha

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

# ④転置行列Transposeとサイズ変更reshape

In [ ]:
# 転置行列
x = torch.rand((4,3))
x

tensor([[0.5246, 0.5019, 0.9414],
        [0.0297, 0.0895, 0.2930],
        [0.4952, 0.5499, 0.6084],
        [0.4911, 0.5228, 0.4929]])

In [ ]:
tx = x.transpose(0,1)

In [ ]:
print(tx)

tensor([[0.5246, 0.0297, 0.4952, 0.4911],
        [0.5019, 0.0895, 0.5499, 0.5228],
        [0.9414, 0.2930, 0.6084, 0.4929]])


参考

In [ ]:
import torch

# 3x3の正則行列を作成
A = torch.tensor([[2, 1, 0], [1, 2, 1], [0, 1, 2]], dtype=torch.float32)

# 行列の逆行列を計算
A_inverse = torch.inverse(A)

# 単位行列を取得するために行列の積を計算
I = A @ A_inverse

print("A:")
print(A)

print("Aの逆行列:")
print(A_inverse)

print("A⋅A^{-1}:")
print(I)

# 単位行列かどうかを確認する
is_identity = torch.allclose(I, torch.eye(3))

print("単位行列か？", is_identity)


A:
tensor([[2., 1., 0.],
        [1., 2., 1.],
        [0., 1., 2.]])
Aの逆行列:
tensor([[ 0.7500, -0.5000,  0.2500],
        [-0.5000,  1.0000, -0.5000],
        [ 0.2500, -0.5000,  0.7500]])
A⋅A^{-1}:
tensor([[ 1.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 2.9802e-08,  1.0000e+00, -5.9605e-08],
        [ 5.9605e-08, -1.1921e-07,  1.0000e+00]])
単位行列か？ False


# reshape

In [ ]:
# 1行16列データを作成
x = torch.ones(16)
x

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# 2行8列データに変換
rex1 = x.reshape(2,8)
rex1

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
# 4行4列データに変換
rex2 = x.reshape(4,-1)
rex2

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# 割り切れないときはエラーになる

In [ ]:
x2 = torch.ones(15)
rex3 = x2.reshape(2,-1)
rex3

RuntimeError: shape '[2, -1]' is invalid for input of size 15